sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install flake8
- pip install coveralls
- pip install -r requirements.txt
script:
- flake8
- coverage run --source=pyIGTLink pyIGTLink/tests.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: aSRWn2XM/+NXBlXhunpICuLuz+edvLt25amUzHo9qVIV9V4WTGmw7EvPZBmE4qNB7QXA3IJuNfpJ48OZv4ZHzm6rIR8zKRsmaZ8+MIREQJIGyHnjEupoz8826cH42hGWCN2H8OcjLxdXSOW3DEZlt7s72cKkOUdnVoTYPX9WHuLBzq5VytH8B39K8UKwE/r7N/RQ6ULgG5RPtoWFA/3XS7+cWF41+ZJDTaa809H3yTmkm67+8fv7rPEgiHVS+5GD6KMMFGom1530VjraGmwfNkzak3xyIhsjY5vMzKVBVKNgzODQRBmDYCWX/CXo/CKA1TWQtsYoescQkmnV69hfEegdD/CaTSEFXaxXShiZ4gebE430nbrx/kAA/3fwkN4eJsF/+PeTY3jVEr1AKuaovcNE9qwhfDTLMYtjuzB7771ndFJA68TaVEJmdGOdKuR6YuDk4Jms/3YXziSiW7KrBBvYWZztQrueD7W9ArPzsp5aQEEfgfsm/C/mr8Nq8GiVp3MFmDpDKetxuNATcuW/MjfiNWXsplzSjWzEZEU4iHXpaL0MsfrSrojbVrrWUVMmOggaEn9sH7fdIERRs24SNVbgyCh2OAEsDGURE6c+4Kiq2NE2sBFEIxxc0jNUcuwVe0F5QLd/ZbGFO96uSgp30N6uE/E/yU4O3VcotAXHRgQ=
  on:
    tags: true
    branch: master
    distributions: sdist bdist_wheel
    repo: Danielhiversen/pyIGTLink
